---
title: {{cookiecutter.project_name}}
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: {{cookiecutter.email}}
description: {{cookiecutter.description}}
url: "https://capitolciderhouse.com"
permalink: pretty
social-media-image: ""
exclude:
- node_modules
- gulpfile.js
logo: ""
