---
title: {{cookiecutter.project_name}}
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
logo:
email: {{cookiecutter.email}}
description: {{cookiecutter.description}}
url:
permalink: pretty
social-media-image:
